BASE_URL = "https://qa-scooter.praktikum-services.ru"
COURIER_CREATE_URL = f"{BASE_URL}/api/v1/courier"
COURIER_LOGIN_URL = f"{BASE_URL}/api/v1/courier/login"
COURIER_DELETE_URL = f"{BASE_URL}/api/v1/courier/"
ORDER_CREATE_URL = f"{BASE_URL}/api/v1/orders"
ORDER_LIST_URL = f"{BASE_URL}/api/v1/orders"
ORDER_ACCEPT_URL = f"{BASE_URL}/api/v1/orders/accept/"
ORDER_GET_BY_TRACK_URL = f"{BASE_URL}/api/v1/orders/track"